/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLi: typeof import('element-plus/es')['ElLi']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUl: typeof import('element-plus/es')['ElUl']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
