server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql:///library?serverTimezone=UTC
    username: root
    password: fc@123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.library.libraryback.entity


# config-location: 指定核心配置文件
#本地存储
#file:
#  storage-location: D:/pic
